services:
  nestjs-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: nestjs-bookstore-dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: ['bun', '--bun', 'dist/main.js']
