name = "nestjs-exercise"
main = "dist/main.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[env.production]]
name = "nestjs-exercise-prod"

[[env.staging]]
name = "nestjs-exercise-staging" 